/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "E:\\workspace\\git\\form-build\\node_modules\\_@vuepress_core@1.5.0@@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "E:\\workspace\\git\\form-build\\node_modules\\_@vuepress_plugin-active-header-links@1.5.0@@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "E:\\workspace\\git\\form-build\\node_modules\\_@vuepress_plugin-nprogress@1.5.0@@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m3 from "E:\\workspace\\git\\form-build\\node_modules\\_vuepress-plugin-demo-block@0.7.2@vuepress-plugin-demo-block\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]