/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "form-build",
  "description": "让表单使用更加简单",
  "base": "/",
  "headTags": [
    [
      "script",
      {
        "src": "https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"
      }
    ],
    [
      "script",
      {
        "src": "https://cdn.jsdelivr.net/npm/@babel/standalone/babel.min.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "指引",
      "frontmatter": {
        "title": "指引"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-5c528977",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "111",
          "slug": "_111"
        },
        {
          "level": 2,
          "title": "222",
          "slug": "_222"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-478d6be4",
      "path": "/"
    },
    {
      "title": "Form-Build 表单生成器",
      "frontmatter": {},
      "regularPath": "/guide/config.html",
      "relativePath": "guide/config.md",
      "key": "v-e87e0828",
      "path": "/guide/config.html",
      "headers": [
        {
          "level": 2,
          "title": "Form props",
          "slug": "form-props"
        }
      ]
    },
    {
      "title": "dsfsdf",
      "frontmatter": {
        "title": "dsfsdf"
      },
      "regularPath": "/guide/install.html",
      "relativePath": "guide/install.md",
      "key": "v-334d0daa",
      "path": "/guide/install.html",
      "headers": [
        {
          "level": 2,
          "title": "npm 安装",
          "slug": "npm-安装"
        },
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "方式一. 全局引入所有UI框架",
          "slug": "方式一-全局引入所有ui框架"
        },
        {
          "level": 3,
          "title": "方式二. 全局按需引入UI框架的组件",
          "slug": "方式二-全局按需引入ui框架的组件"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "安装",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            "/install/"
          ]
        },
        {
          "title": "配置",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            "/config/"
          ]
        }
      ]
    },
    "activeHeaderLinks": true,
    "displayAllHeaders": true
  }
}